name: C/C++ CI

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        working-directory: workspace
    steps:
    - uses: actions/checkout@main
    - name: msvc build
      run: cmake -S . -B .build_x64  -DCMAKE_INSTALL_PREFIX=".build_x64/install" -DCMAKE_BUILD_TYPE=Debug
    - name: cmake build
      run: cmake --build .build_x64  -j  --target install --config Debug
    - name: gzip
      run: |          
        tar -czvf Demo.tar.gz .build_x64/install/
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: Demo.tar.gz application/octet-stream
      env:
          GITHUB_TOKEN: ${{ secrets.release_token }}   





 
