name: C/C++ CI

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@main
    - name: msvc build
      run: cmake -S . -B .build_x64  -DCMAKE_INSTALL_PREFIX=".build_x64/install" -DCMAKE_BUILD_TYPE=Debug
    - name: cmake build
      run: cmake --build .build_x64  -j  --target install --config Debug
    - name: zip
      run: |          
        zip -r Demo .build_x64/install/
    - name: Upload to release
      uses: softprops/action-gh-release@v1      
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          Demo.zip
          LICENSE 





 
