name: C/C++ CI

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@main
    - name: msvc build
      run: cmake -S . -B .build_x64  -DCMAKE_INSTALL_PREFIX=".build_x64/install" -DCMAKE_BUILD_TYPE=Debug
    - name: cmake build
      run: cmake --build .build_x64  -j  --target install --config Debug
    - name: tar
      run: |          
        tar -czvf Demo.tar.gz -C./.build_x64/install *
    - name: Upload to release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        name: ${{ github.ref }}
        files: |
          Demo.tar.gz





 
