name: C/C++ CI

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: cmake init
      run: cmake -S . -B .build_x64  -DCMAKE_INSTALL_PREFIX=".build_x64/install" -DCMAKE_BUILD_TYPE=Debug
    - name: cmake
      run: cmake --build .build_x64  -j  --target install --config Debug
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        token: ${{ secrets.release_token }}
        files: |
          ./build_x64/install/**





 
